const translations = {
    es: {
        // --- Navegación (Claves compartidas) ---
        nav_inicio: "INICIO",
        nav_servicios: "SERVICIOS",
        nav_servicios_cloud: "CLOUD",
        nav_servicios_integrate: "INTEGRATE",
        nav_servicios_data_ai: "DATA+AI",
        nav_servicios_secure: "SECURE",
        nav_servicios_sap: "SAP",
        nav_equipo: "EQUIPO",
        nav_noticias: "NOTICIAS",
        nav_contacto: "CONTACTO",
        // --- Pie de página (Claves compartidas) ---
        footer_copyright: "© 2025 Lamarr Tech. Todos los derechos reservados.",
        
        // --- Página: index.html ---
        // AJUSTE HERO (Punto 1)
        hero_h1: "Conectamos tu ecosistema tecnológico con soporte humano experto.",
        hero_p: "Integramos tus plataformas clave (SAP, Cloud, Data & Apps) para una operación fluida. Te acompañamos con consultores expertos, no con tickets. Garantizamos rendimiento y escalabilidad.",
        // Fin Ajuste Hero
        card_cloud_h3: "Arquitectura Multicloud para tu Negocio",
        card_cloud_p: "Elegimos y combinamos AWS, Google Cloud Platform y Huawei Cloud para construir una infraestructura flexible, eficiente y preparada para crecer. Sin dependencias forzadas. Tú eliges. Tu negocio manda.",
        card_cloud_btn: "Ver Cloud",
        card_integrate_h3: "Integración de tu Ecosistema Tecnológico",
        card_integrate_p: "Conectamos SAP, nube, aplicaciones y datos para que la operación fluya sin silos, sin retrabajos y sin fricción.",
        card_integrate_btn: "Ver Integrate",
        card_data_h3: "Del Dato a la Acción (Data + IA)",
        card_data_p: "Convertimos tus datos en conocimiento accionable. Decisiones más rápidas, precisas y estratégicas con impacto directo en tu operación.",
        card_data_btn: "Ver Data+AI",
        card_secure_h3: "Protección Integral de Datos y Operaciones",
        card_secure_p: "Diseñamos seguridad multinube con control de accesos, respaldo inteligente y monitoreo continuo. Menos riesgo, más continuidad y total visibilidad.",
        card_secure_btn: "Ver Secure",
        card_sap_h3: "Dominio Profundo del Ecosistema SAP",
        card_sap_p: "+20 años de experiencia real en SAP Business One y SAP ECC. Implementamos y optimizamos con criterio y conocimiento de procesos. Resultados desde el día uno.",
        card_sap_btn: "Ver SAP",
        partners_h2: "Aliados que construyen un futuro con Lamarr",
        
        // --- Claves de Mapa y Tabla (ACTUALIZADAS) ---
        map_h3: "Presencia y Capacidad Global", // MODIFICADO
        
        // NUEVAS Claves para la tabla de index.html
        map_table_row1_title: "Chile",
        map_table_row1_desc: "HeadQuarters",
        map_table_row2_title: "Brasil, Costa Rica & Venezuela",
        map_table_row2_desc: "Proyectos SAP, Integración, Operación Multicloud, Soporte Regional",
        map_table_row3_title: "Miami",
        map_table_row3_desc: "Hub de Alianza",
        map_table_row4_title: "India",
        map_table_row4_desc: "Acelerador de Desarrollo",

        map_footer_h4: "Nuestro Compromiso",
        map_footer_q: "\"Tu negocio, impulsado por experiencia global y compromiso real\"",
        
        // --- Página: contact.html ---
        contact_h2: "Iniciemos la Conversación",
        contact_p1: "Has explorado nuestra innovación global en IA y nuestra ejecución experta en Cloud y SAP. Has visto cómo transformamos datos en resultados para líderes de la industria.",
        contact_p2: "Ahora, es tu turno. Cada gran transformación comienza con una simple conversación. Ya sea que tengas un desafío complejo de migración, un proyecto de IA o una consulta sobre optimización, nuestro equipo está listo para escucharte.",
        form_name: "Nombre",
        form_lastname: "Apellido",
        form_email: "Correo electrónico",
        form_phone: "Teléfono (Opcional)",
        form_company: "Nombre de la Empresa (Opcional)",
        form_role: "Cargo (Opcional)",
        form_service: "Servicio de Interés",
        form_service_option: "Selecciona un servicio de interés...",
        form_message: "Mensaje",
        form_submit_btn: "Enviar",
        // NUEVA CLAVE DE CONFIANZA (Punto 2)
        form_response_time: "Recibirás una respuesta de un especialista en menos de 24 horas hábiles.",
        // Fin Nueva Clave
        contact_info_h2: "Información Directa",
        contact_info_company: "Razón Social:", // NUEVA
        contact_info_rut: "Rut:", // NUEVA
        contact_info_giro: "Giro:", // NUEVA
        contact_info_phone: "Teléfono:",
        contact_info_email: "Correo Electrónico:",
        contact_info_address: "Dirección:", // ACTUALIZADA
        popup_title: "¡Gracias por contactarnos!",
        popup_p: "Tu mensaje ha sido enviado. Para una atención más rápida, puedes contactarnos directamente por WhatsApp.",
        popup_btn: "Hablar por WhatsApp",

        // --- Página: lamarr-cloud.html ---
        cloud_h1: "LAMARR | CLOUD",
        cloud_p1: "<strong>Infraestructura sin fricción.</strong><br>Diseñamos, migramos y gestionamos tu arquitectura en AWS, Google Cloud Platform y Huawei Cloud.",
        cloud_p2: "No creemos en una \"talla única\". Seleccionamos la nube (o nubes) que mejor se adapta a tu carga de trabajo (SAP, aplicaciones, datos), optimizando costos y asegurando un rendimiento superior.",
        cloud_s1_h2: "Nuestras Capacidades Cloud",
        cloud_s1_c1_h3: "Migración y Modernización",
        cloud_s1_c1_p: "Planes de migración (Lift & Shift, Re-platform) y modernización de aplicaciones (contenedores, serverless) sin interrumpir tu negocio.",
        cloud_s1_c2_h3: "FinOps y Optimización de Costos",
        cloud_s1_c2_p: "Auditoría continua de tu gasto cloud. Implementamos estrategias FinOps para eliminar desperdicios y reducir tu factura mensual.",
        cloud_s1_c3_h3: "Servicios Gestionados y DevSecOps",
        cloud_s1_c3_p: "Monitoreo 24/7, gestión de parches, seguridad y automatización de pipelines CI/CD. Nos encargamos de la operación para que tú te enfoques en innovar.",
        cloud_s1_c4_h3: "Arquitectura SAP en la Nube",
        cloud_s1_c4_p: "Diseñamos arquitecturas de alta disponibilidad (HA/DR) para SAP S/4HANA y B1 en nubes públicas, certificadas y con rendimiento optimizado.",
        cloud_s1_btn: "Inicia tu migración a la nube",

        // --- Página: lamarr-data-ai.html ---
        data_h1: "LAMARR | DATA+AI",
        data_p1: "Inteligencia que transforma datos en decisiones reales. Integramos nuestra experiencia técnica con soluciones de IA probadas, para que tu negocio escale con IA desde el primer día.",
        data_s1_h3: "Filosofía 360: Múltiplos Puntos de Entrada, Una Sola Dirección",
        data_s1_p: "Entendemos que cada empresa se encuentra en una etapa diferente. Nuestra \"Filosofía 360\" nos permite agregar valor con IA independientemente de su punto de partida, acompañándolo desde la estrategia hasta la ejecución y el escalamiento.",
        data_s2_h2: "Etapas de Madurez",
        data_s2_c1_h3: "DATA READINESS",
        data_s2_c1_p: "Evaluamos tu punto de partida para usar IA con éxito. Realizamos un diagnóstico que analiza tu madurez tecnológica, la calidad de tus datos y la alineación de tu estrategia de IA con los objetivos de negocio.",
        data_s2_c2_h3: "DATALAKE",
        data_s2_c2_p: "Centraliza todos tus datos en una base segura y escalable. Integramos información de SAP, CRM, ERP, hojas de cálculo, aplicaciones web y sensores IoT en un solo entorno limpio y listo para análisis.",
        data_s2_c3_h3: "PREDICT & INSIGHTS",
        data_s2_c3_p: "Ve lo que está pasando y lo que viene. Con modelos predictivos y analítica avanzada, detectamos patrones, anticipamos comportamientos y generamos recomendaciones prácticas.",
        data_s2_c4_h3: "AI SOLUTIONS",
        data_s2_c4_p: "Soluciones Plug & Play de IA listas para usar (scaleAssist, scaleRep) que se integran de inmediato en tus procesos clave, sin desarrollos eternos ni inversiones iniciales altas.",
        data_s2_c5_h3: "AI FACTORY",
        data_s2_c5_p: "Desarrollo a la medida para tu industria. Ponemos a tu disposición equipos especializados en Gen AI, Machine Learning y Data Science para crear soluciones únicas.",
        data_s2_c6_h3: "DATA 360",
        data_s2_c6_p: "Tu ecosistema de datos y IA completo, bajo control. Combina todas nuestras soluciones en un entorno único, escalable y seguro en AWS, Google Cloud Platform o Huawei Cloud.",
        data_s3_h2: "Soluciones IA Plug & Play",
        data_s3_t_h1: "Solución",
        data_s3_t_h2: "Qué hace",
        data_s3_t_h3: "Beneficio inmediato",
        data_s3_t_r1_d1: "Unifica datos de CRM, ERP y fuentes externas para una visión completa.",
        data_s3_t_r1_d2: "Decisiones más rápidas y precisas.",
        data_s3_t_r2_d1: "Agentes de voz IA que califican leads y ejecutan encuestas 24/7.",
        data_s3_t_r2_d2: "Ventas automatizadas y mejor experiencia cliente.",
        data_s3_t_r3_d1: "Reclutamiento inteligente: IA que entrevista, analiza y recomienda.",
        data_s3_t_r3_d2: "Selección más rápida y con menor sesgo.",
        data_s3_t_r4_d1: "Convierte presentaciones en cursos con narración y evaluación IA.",
        data_s3_t_r4_d2: "Formación interna ágil y continua.",
        data_s3_t_r5_d1: "Automatiza gestión documental y validación con IA.",
        data_s3_t_r5_d2: "Ahorro de tiempo y detección de fraudes.",
        data_s3_btn: "Solicita un Assessment",

        // --- Página: lamarr-integrate.html ---
        integrate_h1: "LAMARR | INTEGRATE",
        integrate_p1: "Conectamos tus sistemas, datos y aplicaciones. Creamos flujos de información fluidos entre SAP, tus plataformas cloud y aplicaciones de terceros para una operación unificada.",
        integrate_s1_h2: "Integra tu Ecosistema Tecnológico",
        integrate_s1_p: "En el núcleo de la transformación digital está la integración. LAMARR | INTEGRATE asegura que tus aplicaciones críticas (ERP, CRM, SCM) se comuniquen de manera eficiente, eliminando silos de datos y automatizando procesos de negocio de extremo a extremo.",
        integrate_s1_l1: "<strong>SAP Cloud Platform Integration (CPI):</strong> Diseño y gestión de flujos de integración.",
        integrate_s1_l2: "<strong>Conectividad Híbrida:</strong> Unificamos tus entornos On-Premise y Multi-Cloud.",
        integrate_s1_l3: "<strong>Integración de APIs:</strong> Creamos y gestionamos APIs para conectar tus servicios.",
        integrate_s1_l4: "<strong>Flujos de Datos (ETL/ELT):</strong> Movemos tus datos de forma segura para analítica y IA.",
        integrate_s1_btn: "Conecta tu ecosistema hoy",

        // --- Página: lamarr-secure.html ---
        secure_h1: "LAMARR | SECURE",
        secure_p1: "Ciberprotección nativa para tu negocio. Ofrecemos una plataforma integrada de backup, DR, seguridad avanzada y monitoreo continuo, potenciada por las mejores alianzas tecnológicas, para proteger tus datos, aplicaciones y sistemas.",
        secure_s1_h2: "Productos y Servicios de Ciberprotección",
        secure_s1_c1_h3: "Cyber Backup & Recovery",
        secure_s1_c1_p: "Copias de seguridad rápidas y fiables de cualquier carga de trabajo. Almacenamiento seguro en nuestra nube, AWS, GCP o local, con restauración instantánea de datos críticos.",
        secure_s1_c2_h3: "Disaster Recovery (DRaaS)",
        secure_s1_c2_p: "Recuperación ante desastres como servicio. Minimice el tiempo de inactividad y garantice la continuidad del negocio con conmutación por error a nuestra plataforma en la nube.",
        secure_s1_c3_h3: "Advanced Security",
        secure_s1_c3_p: "Protección proactiva contra ransomware y malware impulsada por IA. Antivirus, antimalware y análisis de vulnerabilidades en una sola solución.",
        secure_s1_c4_h3: "Endpoint Defense",
        secure_s1_c4_p: "Protección inteligente en cada dispositivo. Protección con IA para estaciones de trabajo y servidores contra malware, phishing y amenazas desconocidas.",
        secure_s1_c5_h3: "SaaS Protect",
        secure_s1_c5_p: "Protección completa para Microsoft 365 y Google Workspace. Garantizamos backups nube a nube para correos, archivos (OneDrive, SharePoint) y colaboraciones (Teams).",
        secure_s1_btn: "Agenda una evaluación",

        // --- Página: noticias.html ---
        news_h1: "Noticias: Lo que estamos construyendo",
        news_p1: "Crecemos junto a nuestros partners, nuestros clientes y nuestra comunidad. Cada paso fortalece nuestra capacidad de entregar soluciones integradas, seguras y escalables en SAP, Cloud e IA.",
        
        news_s1_h2: "Nuevas Alianzas Estratégicas",
        news_s1_c1_h3: "Lamarr + WIT: Alianza para Desarrollo de Nuevos Negocios",
        news_s1_c1_p: "Hemos formalizado una alianza con WIT para fortalecer la apertura y calificación de oportunidades comerciales en Chile y LATAM. Este trabajo conjunto nos permite llegar a empresas que buscan modernizar SAP y escalar hacia arquitecturas multicloud, con acompañamiento consultivo y visión estratégica.",
        news_s1_c2_h3: "Lamarr + La Araucaria Software: Soluciones Conjuntas en Ciberseguridad",
        news_s1_c2_p: "Junto a La Araucaria Software, estamos desarrollando soluciones orientadas a ciberseguridad aplicada, protección de datos críticos y monitoreo inteligente de riesgos. La combinación de ingeniería segura + integración SAP + arquitectura cloud nos permite entregar soluciones escalables, eficientes y alineadas a los desafíos actuales.",
        news_s1_c3_h3: "Convenio Marco con Noventiq",
        news_s1_c3_p: "Este convenio formaliza nuestra capacidad de ejecutar proyectos SAP + Cloud de manera conjunta, asegurando continuidad, trazabilidad y escalabilidad en la entrega de servicios.",
        
        news_s2_h2: "Eventos y Noticias Pasadas",
        news_s2_c1_h3: "Huawei Cloud reconoce a Lamarr como Partner con Potencial",
        news_s2_c1_p: "Lamarr participó en el Huawei Cloud Summit, donde fuimos reconocidos como Partner con Potencial en la región por nuestra experiencia en modernización SAP, estrategias multicloud y arquitecturas híbridas. Este hito refleja nuestro compromiso con soluciones de alto impacto, con ejecución técnica propia y acompañamiento continuo.",
        news_s2_c1_alt: "Certificado Huawei Cloud Partner Lamarr Tech",
        news_s2_c2_h3: "Evento Presencial: SAP Business One en Huawei Cloud",
        news_s2_c2_p: "Realizamos un encuentro ejecutivo enfocado en organizaciones que operan SAP Business One y buscan optimizar su infraestructura en la nube. El evento se centró en presentar rutas de transición claras, casos de éxito reales y modelos de arquitectura eficientes en Huawei Cloud.",
        news_s2_c2_btn: "Leer más y ver video",
        news_s2_c3_h3: "Webinar Ejecutivo junto a Noventiq: El Fin de Soporte de SAP ECC",
        news_s2_c3_p: "En un encuentro ejecutivo reciente, conversamos junto a Noventiq sobre el fin de soporte de SAP ECC, sus implicancias y las opciones de transición hacia SAP en la nube. El enfoque fue claro: tomar decisiones informadas, no apresuradas.",
        
        // --- TEXTO ACTUALIZADO PARA EL EVENTO SAP B1 ---
        news_s3_h2: "Próximos Eventos",
        news_s3_c1_h3: "Webinar Exclusivo: Potencia tu SAP Business One en la Nube",
        news_s3_c1_s: "Estrategias de Migración, Optimización y Ahorro",
        news_s3_c1_p: "<strong>¿Tu infraestructura actual limita el crecimiento de tu negocio?</strong><br>Descubre cómo migrar SAP Business One a la nube puede reducir costos operativos, mejorar la seguridad y garantizar la continuidad de tu operación. En esta sesión, exploraremos las rutas de migración más eficientes y cómo aprovechar al máximo las capacidades de la nube.",
        news_s3_c1_l1: "<strong>Migración sin fricción:</strong> Pasos clave para una transición segura.",
        news_s3_c1_l2: "<strong>Ahorro y Rendimiento:</strong> Cómo optimizar recursos y mejorar la velocidad.",
        news_s3_c1_l3: "<strong>Casos de Éxito:</strong> Empresas que ya transformaron su operación.",
        news_s3_c1_btn: "→ Reserva tu cupo ahora",
        // -----------------------------------------------

        news_cierre: "En Lamarr avanzamos con una visión clara:<br>Tecnologia integrada. Operación fluida.<br>Ejecución responsable y acompañamiento real.",
        news_cta_h3: "No te pierdas nuestras futuras invitaciones",
        news_cta_p: "Si no quieres perderte nuestros próximos eventos y quieres que te invitemos directamente a tu correo, regístrate en nuestra página de contacto.",
        news_cta_btn: "Inscríbete aquí",

        // --- Página: nuestro-equipo.html ---
        team_h1: "Nuestro Equipo",
        team_p1: "Conoce a los líderes y las unidades que impulsan la innovación en Lamarr Tech.",
        team_s1_h2: "Dirección y Estrategia",
        team_s1_c1_h3: "Daniela Santos Escalona",
        team_s1_c1_r: "Founder & CEO | Gerente Comercial",
        team_s1_c1_p: "Lidera la estrategia global de Lamarr Tech, alianzas con AWS, Google Cloud Platform y Huawei, desarrollo de mercado y relación directa con clientes medianos y grandes. Responsable del posicionamiento comercial, propuestas de valor, negociaciones y cierre de oportunidades estratégicas.",
        team_s1_c2_h3: "Alcides Lizardo",
        team_s1_c2_r: "Co-Founder | Director de Operaciones y Finanzas",
        team_s1_c2_p: "Responsable de la operación interna de proyectos, finanzas, control de costos, contratación de personal, relaciones con proveedores y aseguramiento de calidad. Supervisa las áreas técnicas y el cumplimiento de los SLA en servicios gestionados.",
        team_s2_h2: "Unidad LAMARR | CLOUD",
        team_s2_p: "(Infraestructura, migraciones y soporte Cloud – AWS, Google Cloud Platform, Huawei Cloud)",
        team_s2_c1_h3: "Arquitecto Cloud / Líder Técnico",
        team_s2_c1_r: "(Rol variable por proyecto)",
        team_s2_c1_p: "Diseño de arquitecturas en nube, evaluaciones de infraestructura (AWS OLA, MAP, GCP Assessment), planes de migración y soporte avanzado. (Este rol puede ser personalizado según proyecto: Ej. Arquitecto AWS Senior, Arquitecto GCP, etc.)",
        team_s2_c2_h3: "Consultores Cloud y DevOps",
        team_s2_c2_r: "Implementación y Operación",
        team_s2_c2_p: "Implementación de entornos, automatización, optimización de costos, monitoreo, backup & DRP, seguridad gestionada y administración diaria de plataformas cloud.",
        team_s3_h2: "Unidad LAMARR | SAP",
        team_s3_p: "(Consultoría, soporte y migraciones SAP Business One & SAP S/4HANA)",
        team_s3_c1_h3: "Consultor SAP Business One Senior",
        team_s3_c1_r: "Funcional y Procesos",
        team_s3_c1_p: "Lidera diagnósticos funcionales, levantamiento de procesos, parametrización y mejoras operacionales.",
        team_s3_c2_h3: "Consultor SAP Business One Técnico / Basis",
        team_s3_c2_r: "Administración y Soporte Técnico",
        team_s3_c2_p: "Administración de servidores SAP B1, instalación, upgrades, performance tuning y soporte técnico.",
        team_s3_c3_h3: "Consultor SAP Integraciones",
        team_s3_c3_r: "(SAP BTP / APIs / Conectores)",
        team_s3_c3_p: "Diseño e implementación de integraciones entre SAP y sistemas externos (ERP, logística, finanzas, BI, IA).",
        team_s4_h2: "Unidad DATA + AI | Inteligencia y Automatización",
        team_s4_p: "(Modelos predictivos, reporting financiero, cuadros de mando y RPA/IA)",
        team_s4_c1_h3: "Data Engineer / BI Specialist",
        team_s4_c1_r: "Ingeniería y Visualización",
        team_s4_c1_p: "Modelado de datos, construcción de ETL, dashboards dinámicos (Power BI, Looker, ModelArts, QuickSight).",
        team_s4_c2_h3: "Especialista en IA Aplicada",
        team_s4_c2_r: "Automatización Inteligente",
        team_s4_c2_p: "Automatización de procesos, generación de reportes inteligentes, asistentes empresariales y motores de análisis basados en IA.",
        team_s5_h2: "Unidad Administración & Control",
        team_s5_c1_h3: "Coordinación Administrativa",
        team_s5_c1_r: "Gestión y Finanzas",
        team_s5_c1_p: "Gestión de proveedores, control de pagos, emisión de documentos contables, reportes internos, conciliaciones y soporte administrativo a las unidades de negocio.",
        team_s5_c2_h3: "Soporte Operativo y Gestión de Proyectos",
        team_s5_c2_r: "Planificación y Seguimiento",
        team_s5_c2_p: "Planificación de tareas, coordinación entre equipo técnico y clientes, seguimiento de SLA y entregables.",

        // --- Página: services-sap.html ---
        sap_h1: "LAMARR | SAP",
        sap_s1: "El poder de SAP, llevado a su máximo desempeño.",
        sap_p1: "Acompañamos a empresas que operan SAP en evolucionar hacia un sistema más eficiente, integrado y preparado para crecer.",
        sap_p2: "Combinamos experiencia operativa en SAP con dominio de las nuevas soluciones SAP BTP para integrar, automatizar y escalar tu negocio. Diseñamos entornos SAP que se adaptan a tu estrategia y no al revés.",
        sap_s2_h2: "Nuestros Servicios SAP",
        sap_s2_c1_h3: "Consultoría Funcional & Mejora de Procesos",
        sap_s2_c1_p: "Optimizamos tu operación financiera, logística, contable y de abastecimiento para simplificar, controlar y acelerar tareas clave.",
        sap_s2_c2_h3: "Implementación y Actualización de Versiones",
        sap_s2_c2_l1: "Implementación y reparametrización en SAP Business One",
        sap_s2_c2_l2: "Migración a SAP B1 10.0 (SQL / HANA)",
        sap_s2_c2_l3: "Evolución de SAP ECC hacia S/4 HANA",
        sap_s2_c3_h3: "Soporte Técnico & Performance SAP",
        sap_s2_c3_p: "Administración de bases de datos, tuning, resolución de incidencias y continuidad operativa. Estabilidad y rendimiento 24/7.",
        sap_s2_c4_h3: "SAP BTP & Conectividad",
        sap_s2_c4_p: "Integramos SAP con CRM, e-commerce, aplicaciones internas y nube. Automatización, APIs, workflows y datos centralizados.",
        sap_s2_c5_h3: "SAP en la Nube (AWS, Google Cloud Platform, Huawei Cloud)",
        sap_s2_c5_p: "Arquitecturas seguras, escalables y de alta disponibilidad, con optimización FinOps para reducir costos.",
        sap_s3_h2: "Casos Reales",
        sap_s3_l1: "Migramos SAP Business One a AWS, reduciendo un 35% los costos y habilitando acceso remoto seguro para todas las áreas.",
        sap_s3_l2: "Integración SAP + e-commerce, logrando actualización automática de inventarios y pedidos en tiempo real.",
        sap_s3_l3: "Optimización de procesos financieros en SAP ECC, reduciendo tiempos de cierre contable en un 60%.",
        sap_p3: "Tu SAP puede ser más eficiente, más conectado y más rentable. Nosotros te acompañamos en el camino.",
        sap_s3_btn: "Tu evolución SAP comienza aquí."
    },
    en: {
        // --- Navegación (Claves compartidas) ---
        nav_inicio: "HOME",
        nav_servicios: "SERVICES",
        nav_servicios_cloud: "CLOUD",
        nav_servicios_integrate: "INTEGRATE",
        nav_servicios_data_ai: "DATA+AI",
        nav_servicios_secure: "SECURE",
        nav_servicios_sap: "SAP",
        nav_equipo: "TEAM",
        nav_noticias: "NEWS",
        nav_contacto: "CONTACT",
        // --- Pie de página (Claves compartidas) ---
        footer_copyright: "© 2025 Lamarr Tech. All rights reserved.",
        
        // --- Página: index.html ---
        // AJUSTE HERO (Punto 1) - Revisión de tono (Punto 4)
        hero_h1: "We connect your technology ecosystem with expert human support.",
        hero_p: "We integrate your key platforms (SAP, Cloud, Data & Apps) for fluid operations. We support you with expert consultants, not tickets. We guarantee performance and scalability.",
        // Fin Ajuste Hero
        card_cloud_h3: "Multicloud Architecture",
        card_cloud_p: "We select and combine AWS, Google Cloud Platform, and Huawei Cloud to build a flexible, efficient, and growth-ready infrastructure. No forced dependencies. You choose. Your business commands.",
        card_cloud_btn: "View Cloud",
        // AJUSTE INTEGRATE (Punto 4) - Cambio de "Integration of your Tech Ecosystem" a "Ecosystem Integration Services"
        card_integrate_h3: "Ecosystem Integration Services",
        card_integrate_p: "We connect SAP, cloud, applications, and data so operations flow without silos, rework, or friction.",
        card_integrate_btn: "View Integrate",
        card_data_h3: "Data & Applied AI",
        card_data_p: "We turn your data into actionable insights. Faster, more accurate, and strategic decisions with direct impact on your operation.",
        card_data_btn: "View Data+AI",
        card_secure_h3: "Comprehensive Cybersecurity",
        card_secure_p: "We design multicloud security with access control, smart backup, and continuous monitoring. Less risk, more continuity, and total visibility.",
        card_secure_btn: "View Secure",
        card_sap_h3: "Deep SAP Expertise",
        card_sap_p: "20+ years of real experience in SAP Business One and SAP ECC. We implement and optimize with criteria and process knowledge. Results from day one.",
        card_sap_btn: "View SAP",
        partners_h2: "Allies building a future with Lamarr",
        
        // --- Claves de Mapa y Tabla (ACTUALIZADAS) ---
        map_h3: "Global Presence and Capability", 

        // NUEVAS Claves para la tabla de index.html
        map_table_row1_title: "Chile",
        map_table_row1_desc: "HeadQuarters",
        map_table_row2_title: "Brazil, Costa Rica & Venezuela",
        map_table_row2_desc: "SAP Projects, Integration, Multicloud Operation, Regional Support",
        map_table_row3_title: "Miami",
        map_table_row3_desc: "Alliance Hub",
        map_table_row4_title: "India",
        map_table_row4_desc: "Development Accelerator",

        map_footer_h4: "Our Commitment",
        map_footer_q: "\"Your business, driven by global experience and real commitment\"",
        
        // --- Página: contact.html ---
        contact_h2: "Let's Start the Conversation",
        contact_p1: "You've explored our global innovation in AI and our expert execution in Cloud and SAP. You've seen how we transform data into results for industry leaders.",
        contact_p2: "Now, it's your turn. Every great transformation begins with a simple conversation. Whether you have a complex migration challenge, an AI project, or an optimization query, our team is ready to listen.",
        form_name: "Name",
        form_lastname: "Last Name",
        form_email: "Email address",
        form_phone: "Phone (Optional)",
        form_company: "Company Name (Optional)",
        form_role: "Role (Optional)",
        form_service: "Service of Interest",
        form_service_option: "Select a service of interest...",
        form_message: "Message",
        form_submit_btn: "Send",
        // NUEVA CLAVE DE CONFIANZA (Punto 2)
        form_response_time: "You will receive a response from a specialist in less than 24 business hours.",
        // Fin Nueva Clave
        contact_info_h2: "Direct Information",
        contact_info_company: "Business Name:", 
        contact_info_rut: "Tax ID:", 
        contact_info_giro: "Business Activity:", 
        contact_info_phone: "Phone:",
        contact_info_email: "Email:",
        contact_info_address: "Address:", 
        popup_title: "Thank you for contacting us!",
        popup_p: "Your message has been sent. For faster assistance, you can contact us directly on WhatsApp.",
        popup_btn: "Chat on WhatsApp",

        // --- Página: lamarr-cloud.html ---
        cloud_h1: "LAMARR | CLOUD",
        cloud_p1: "<strong>Frictionless Infrastructure.</strong><br>We design, migrate, and manage your architecture on AWS, Google Cloud Platform, and Huawei Cloud.",
        cloud_p2: "We don't believe in \"one size fits all.\" We select the cloud (or clouds) that best fits your workload (SAP, applications, data), optimizing costs and ensuring superior performance.",
        cloud_s1_h2: "Our Cloud Capabilities",
        cloud_s1_c1_h3: "Migration and Modernization",
        cloud_s1_c1_p: "Migration plans (Lift & Shift, Re-platform) and application modernization (containers, serverless) without disrupting your business.",
        cloud_s1_c2_h3: "FinOps and Cost Optimization",
        cloud_s1_c2_p: "Continuous audit of your cloud spending. We implement FinOps strategies to eliminate waste and reduce your monthly bill.",
        card_cloud_h3: "Managed Services and DevSecOps", // Reajustado card_cloud_h3 para tono
        cloud_s1_c3_p: "24/7 monitoring, patch management, security, and CI/CD pipeline automation. We handle operations so you can focus on innovation.",
        cloud_s1_c4_h3: "SAP Architecture on Cloud",
        cloud_s1_c4_p: "We design high-availability (HA/DR) architectures for SAP S/4HANA and B1 on public clouds, certified and performance-optimized.",
        cloud_s1_btn: "Start your cloud migration",

        // --- Página: lamarr-data-ai.html ---
        data_h1: "LAMARR | DATA+AI",
        data_p1: "Intelligence that transforms data into real decisions. We integrate our technical expertise with proven AI solutions, so your business can scale with AI from day one.",
        data_s1_h3: "360 Philosophy: Multiple Entry Points, One Direction",
        data_s1_p: "We understand that every company is at a different stage. Our \"360 Philosophy\" allows us to add value with AI regardless of your starting point, guiding you from strategy to execution and scaling.",
        data_s2_h2: "Maturity Stages",
        data_s2_c1_h3: "DATA READINESS",
        data_s2_c1_p: "We assess your starting point for using AI successfully. We conduct a diagnosis that analyzes your technological maturity, data quality, and the alignment of your AI strategy with business objectives.",
        data_s2_c2_h3: "DATALAKE",
        data_s2_c2_p: "Centralize all your data in a secure and scalable foundation. We integrate information from SAP, CRM, ERP, spreadsheets, web applications, and IoT sensors into a single, clean environment ready for analysis.",
        data_s2_c3_h3: "PREDICT & INSIGHTS",
        data_s2_c3_p: "See what's happening and what's next. With predictive models and advanced analytics, we detect patterns, anticipate behaviors, and generate practical recommendations.",
        data_s2_c4_h3: "AI SOLUTIONS",
        data_s2_c4_p: "Plug & Play AI solutions ready to use (scaleAssist, scaleRep) that integrate immediately into your key processes, without endless development or high initial investments.",
        data_s2_c5_h3: "AI FACTORY",
        data_s2_c5_p: "Custom development for your industry. We provide specialized teams in Gen AI, Machine Learning, and Data Science to create unique solutions.",
        data_s2_c6_h3: "DATA 360",
        data_s2_c6_p: "Your complete data and AI ecosystem, under control. Combine all our solutions in a single, scalable, and secure environment on AWS, Google Cloud Platform, or Huawei Cloud.",
        data_s3_h2: "Plug & Play AI Solutions",
        data_s3_t_h1: "Solution",
        data_s3_t_h2: "What it does",
        data_s3_t_h3: "Immediate Benefit",
        data_s3_t_r1_d1: "Unifies data from CRM, ERP, and external sources for a complete view.",
        data_s3_t_r1_d2: "Faster and more accurate decisions.",
        data_s3_t_r2_d1: "AI voice agents that qualify leads and conduct surveys 24/7.",
        data_s3_t_r2_d2: "Automated sales and improved customer experience.",
        data_s3_t_r3_d1: "Smart recruiting: AI that interviews, analyzes, and recommends.",
        data_s3_t_r3_d2: "Faster selection with less bias.",
        data_s3_t_r4_d1: "Converts presentations into courses with AI narration and evaluation.",
        data_s3_t_r4_d2: "Agile and continuous internal training.",
        data_s3_t_r5_d1: "Automates document management and validation with AI.",
        data_s3_t_r5_d2: "Time savings and fraud detection.",
        data_s3_btn: "Request an Assessment",

        // --- Página: lamarr-integrate.html ---
        integrate_h1: "LAMARR | INTEGRATE",
        integrate_p1: "We connect your systems, data, and applications. We create fluid information flows between SAP, your cloud platforms, and third-party applications for unified operation.",
        integrate_s1_h2: "Integrate Your Technology Ecosystem",
        integrate_s1_p: "At the core of digital transformation is integration. LAMARR | INTEGRATE ensures your critical applications (ERP, CRM, SCM) communicate efficiently, eliminating data silos and automating end-to-end business processes.",
        integrate_s1_l1: "<strong>SAP Cloud Platform Integration (CPI):</strong> Design and management of integration flows.",
        integrate_s1_l2: "<strong>Hybrid Connectivity:</strong> We unify your On-Premise and Multi-Cloud environments.",
        integrate_s1_l3: "<strong>API Integration:</strong> We create and manage APIs to connect your services.",
        integrate_s1_l4: "<strong>Data Flows (ETL/ELT):</strong> We move your data securely for analytics and AI.",
        integrate_s1_btn: "Connect your ecosystem today",

        // --- Página: lamarr-secure.html ---
        secure_h1: "LAMARR | SECURE",
        secure_p1: "Native cyber-protection for your business. We offer an integrated platform for backup, DR, advanced security, and continuous monitoring, powered by the best technology alliances, to protect your data, applications, and systems.",
        secure_s1_h2: "Cyber-protection Products and Services",
        secure_s1_c1_h3: "Cyber Backup & Recovery",
        secure_s1_c1_p: "Fast and reliable backups of any workload. Secure storage in our cloud, AWS, GCP, or local, with instant restoration of critical data.",
        secure_s1_c2_h3: "Disaster Recovery (DRaaS)",
        secure_s1_c2_p: "Disaster Recovery as a Service. Minimize downtime and ensure business continuity with failover to our cloud platform.",
        secure_s1_c3_h3: "Advanced Security",
        secure_s1_c3_p: "Proactive, AI-driven protection against ransomware and malware. Antivirus, antimalware, and vulnerability analysis in one solution.",
        secure_s1_c4_h3: "Endpoint Defense",
        secure_s1_c4_p: "Intelligent protection on every device. AI-powered protection for workstations and servers against malware, phishing, and unknown threats.",
        secure_s1_c5_h3: "SaaS Protect",
        secure_s1_c5_p: "Complete protection for Microsoft 365 and Google Workspace. We guarantee cloud-to-cloud backups for emails, files (OneDrive, SharePoint), and collaborations (Teams).",
        secure_s1_btn: "Schedule an assessment",

        // --- Página: noticias.html ---
        news_h1: "News: What we are building",
        news_p1: "We grow alongside our partners, our clients, and our community. Each step strengthens our ability to deliver integrated, secure, and scalable solutions in SAP, Cloud, and AI.",
        
        news_s1_h2: "New Strategic Alliances",
        news_s1_c1_h3: "Lamarr + WIT: Alliance for New Business Development",
        news_s1_c1_p: "We have formalized an alliance with WIT to strengthen the opening and qualification of business opportunities in Chile and LATAM. This joint effort allows us to reach companies looking to modernize SAP and scale to multicloud architectures, with consultative support and strategic vision.",
        news_s1_c2_h3: "Lamarr + La Araucaria Software: Joint Solutions in Cybersecurity",
        news_s1_c2_p: "Together with La Araucaria Software, we are developing solutions focused on applied cybersecurity, critical data protection, and intelligent risk monitoring. The combination of secure engineering + SAP integration + cloud architecture allows us to deliver scalable, efficient solutions aligned with current challenges.",
        news_s1_c3_h3: "Framework Agreement with Noventiq",
        news_s1_c3_p: "This agreement formalizes our ability to jointly execute SAP + Cloud projects, ensuring continuity, traceability, and scalability in service delivery.",
        
        news_s2_h2: "Past Events and News",
        news_s2_c1_h3: "Huawei Cloud recognizes Lamarr as a Partner with Potential",
        news_s2_c1_p: "Lamarr participated in the Huawei Cloud Summit, where we were recognized as a Partner with Potential in the region for our experience in SAP modernization, multicloud strategies, and hybrid architectures. This milestone reflects our commitment to high-impact solutions, with our own technical execution and continuous support.",
        news_s2_c1_alt: "Lamarr Tech Huawei Cloud Partner Certificate", 
        news_s2_c2_h3: "In-Person Event: SAP Business One on Huawei Cloud",
        news_s2_c2_p: "We held an executive meeting aimed at organizations operating SAP Business One that wish to migrate or optimize their cloud infrastructure, maintaining operational continuity and cost control. We presented transition paths, real cases, and architecture models.",
        news_s2_c2_btn: "Read more and see video",
        news_s2_c3_h3: "Executive Webinar with Noventiq: The End of Support for SAP ECC",
        news_s2_c3_p: "In a recent executive meeting, we discussed with Noventiq the end of support for SAP ECC, its implications, and the options for transitioning to SAP on the cloud. The focus was clear: make informed decisions, not rushed ones.",
        
        // --- UPDATE: English Text for SAP B1 Webinar ---
        news_s3_h2: "Upcoming Events",
        news_s3_c1_h3: "Exclusive Webinar: Boost Your SAP Business One in the Cloud",
        news_s3_c1_s: "Strategies for Migration, Optimization, and Savings",
        news_s3_c1_p: "<strong>Is your current infrastructure limiting your business growth?</strong><br>Discover how migrating SAP Business One to the cloud can reduce operating costs, improve security, and ensure operational continuity. In this session, we will explore efficient migration paths and how to leverage cloud capabilities fully.",
        news_s3_c1_l1: "<strong>Frictionless Migration:</strong> Key steps for a secure transition.",
        news_s3_c1_l2: "<strong>Savings and Performance:</strong> How to optimize resources and improve speed.",
        news_s3_c1_l3: "<strong>Success Stories:</strong> Companies that have already transformed their operations.",
        news_s3_c1_btn: "→ Reserve your spot now",
        // -----------------------------------------------

        news_cierre: "At Lamarr, we move forward with a clear vision:<br>Integrated technology. Fluid operation.<br>Responsible execution and real support.",
        news_cta_h3: "Don't miss our future invitations",
        news_cta_p: "If you don't want to miss our upcoming events and want to be invited directly to your email, register on our contact page.",
        news_cta_btn: "Register here",

        // --- Página: nuestro-equipo.html ---
        team_h1: "Our Team",
        team_p1: "Meet the leaders and units driving innovation at Lamarr Tech.",
        team_s1_h2: "Direction and Strategy",
        team_s1_c1_h3: "Daniela Santos Escalona",
        team_s1_c1_r: "Founder & CEO | Commercial Manager",
        team_s1_c1_p: "Leads Lamarr Tech's global strategy, alliances with AWS, Google Cloud Platform, and Huawei, market development, and direct relationships with medium and large clients. Responsible for commercial positioning, value propositions, negotiations, and closing strategic opportunities.",
        team_s1_c2_h3: "Alcides Lizardo",
        team_s1_c2_r: "Co-Founder | Director of Operations and Finance",
        team_s1_c2_p: "Responsible for internal project operations, finance, cost control, personnel hiring, supplier relations, and quality assurance. Supervises technical areas and compliance with SLAs in managed services.",
        team_s2_h2: "LAMARR | CLOUD Unit",
        team_s2_p: "(Infrastructure, migrations, and Cloud support – AWS, Google Cloud Platform, Huawei Cloud)",
        team_s2_c1_h3: "Cloud Architect / Technical Lead",
        team_s2_c1_r: "(Role varies by project)",
        team_s2_c1_p: "Design of cloud architectures, infrastructure assessments (AWS OLA, MAP, GCP Assessment), migration plans, and advanced support. (This role can be customized per project: e.g., Senior AWS Architect, GCP Architect, etc.)",
        team_s2_c2_h3: "Cloud and DevOps Consultants",
        team_s2_c2_r: "Implementation and Operation",
        team_s2_c2_p: "Implementation of environments, automation, cost optimization, monitoring, backup & DRP, managed security, and daily administration of cloud platforms.",
        team_s3_h2: "LAMARR | SAP Unit",
        team_s3_p: "(Consulting, support, and migrations for SAP Business One & SAP S/4HANA)",
        team_s3_c1_h3: "Senior SAP Business One Consultant",
        team_s3_c1_r: "Functional and Processes",
        team_s3_c1_p: "Leads functional diagnostics, process mapping, parameterization, and operational improvements.",
        team_s3_c2_h3: "SAP Business One Technical / Basis Consultant",
        team_s3_c2_r: "Administration and Technical Support",
        team_s3_c2_p: "Administration of SAP B1 servers, installation, upgrades, performance tuning, and technical support.",
        team_s3_c3_h3: "SAP Integrations Consultant",
        team_s3_c3_r: "(SAP BTP / APIs / Connectors)",
        team_s3_c3_p: "Design and implementation of integrations between SAP and external systems (ERP, logistics, finance, BI, AI).",
        team_s4_h2: "DATA + AI Unit | Intelligence and Automation",
        team_s4_p: "(Predictive models, financial reporting, dashboards, and RPA/AI)",
        team_s4_c1_h3: "Data Engineer / BI Specialist",
        team_s4_c1_r: "Engineering and Visualization",
        team_s4_c1_p: "Data modeling, ETL construction, dynamic dashboards (Power BI, Looker, ModelArts, QuickSight).",
        team_s4_c2_h3: "Applied AI Specialist",
        team_s4_c2_r: "Intelligent Automation",
        team_s4_c2_p: "Process automation, intelligent report generation, business assistants, and AI-based analysis engines.",
        team_s5_h2: "Administration & Control Unit",
        team_s5_c1_h3: "Administrative Coordination",
        team_s5_c1_r: "Management and Finance",
        team_s5_c1_p: "Supplier management, payment control, issuance of accounting documents, internal reports, reconciliations, and administrative support to business units.",
        team_s5_c2_h3: "Operational Support and Project Management",
        team_s5_c2_r: "Planning and Monitoring",
        team_s5_c2_p: "Task planning, coordination between technical team and clients, monitoring of SLAs and deliverables.",

        // --- Página: services-sap.html ---
        sap_h1: "LAMARR | SAP",
        sap_s1: "The power of SAP, taken to its maximum performance.",
        sap_p1: "We help companies running SAP to evolve towards a more efficient, integrated, and growth-ready system.",
        sap_p2: "We combine operational experience in SAP with mastery of new SAP BTP solutions to integrate, automate, and scale your business. We design SAP environments that adapt to your strategy, not the other way around.",
        sap_s2_h2: "Our SAP Services",
        sap_s2_c1_h3: "Functional Consulting & Process Improvement",
        sap_s2_c1_p: "We optimize your financial, logistics, accounting, and supply operations to simplify, control, and accelerate key tasks.",
        sap_s2_c2_h3: "Implementation and Version Upgrades",
        sap_s2_c2_l1: "Implementation and re-parameterization in SAP Business One",
        sap_s2_c2_l2: "Migration to SAP B1 10.0 (SQL / HANA)",
        sap_s2_c2_l3: "Evolution from SAP ECC to S/4 HANA",
        sap_s2_c3_h3: "Technical Support & SAP Performance",
        sap_s2_c3_p: "Database administration, tuning, incident resolution, and operational continuity. 24/7 stability and performance.",
        sap_s2_c4_h3: "SAP BTP & Connectivity",
        sap_s2_c4_p: "We integrate SAP with CRM, e-commerce, internal applications, and the cloud. Automation, APIs, workflows, and centralized data.",
        sap_s2_c5_h3: "SAP on the Cloud (AWS, Google Cloud Platform, Huawei Cloud)",
        sap_s2_c5_p: "Secure, scalable, and high-availability architectures, with FinOps optimization to reduce costs.",
        sap_s3_h2: "Real Cases",
        sap_s3_l1: "We migrated SAP Business One to AWS, reducing costs by 35% and enabling secure remote access for all areas.",
        sap_s3_l2: "SAP + e-commerce integration, achieving automatic inventory and order updates in real-time.",
        sap_s3_l3: "Optimization of financial processes in SAP ECC, reducing accounting closing times by 60%.",
        sap_p3: "Your SAP can be more efficient, more connected, and more profitable. We guide you on the way.",
        sap_s3_btn: "Your SAP evolution starts here."
    },
    pt: {
        // --- Navegação (Chaves compartilhadas) ---
        nav_inicio: "INÍCIO",
        nav_servicios: "SERVIÇOS",
        nav_servicios_cloud: "NUVEM",
        nav_servicios_integrate: "INTEGRATE",
        nav_servicios_data_ai: "DATA+AI",
        nav_servicios_secure: "SECURE",
        nav_servicios_sap: "SAP",
        nav_equipo: "EQUIPE",
        nav_noticias: "NOTÍCIAS",
        nav_contacto: "CONTATO",
        // --- Rodapé (Chaves compartilhadas) ---
        footer_copyright: "© 2025 Lamarr Tech. Todos os direitos reservados.",
        
        // --- Página: index.html ---
        // AJUSTE HERO (Punto 1) - Revisión de tono (Punto 4)
        hero_h1: "Conectamos seu ecossistema tecnológico com suporte humano especializado.",
        hero_p: "Integramos suas plataformas-chave (SAP, Nuvem, Dados e Apps) para uma operação fluida. Acompanhamos você com consultores especializados, não com tickets. Garantimos desempenho e escalabilidade.",
        // Fin Ajuste Hero
        card_cloud_h3: "Arquitetura Multicloud para o seu Negócio",
        card_cloud_p: "Escolhemos e combinamos AWS, Google Cloud Platform e Huawei Cloud para construir uma infraestrutura flexível, eficiente e pronta para crescer. Sem dependências forçadas. Você escolhe. O seu negócio manda.",
        card_cloud_btn: "Ver Nuvem",
        // AJUSTE INTEGRATE (Punto 4) - Cambio de "Integração do seu Ecossistema Tecnológico" a "Serviços de Integração de Ecossistema"
        card_integrate_h3: "Serviços de Integração de Ecossistema",
        card_integrate_p: "Conectamos SAP, nuvem, aplicativos e dados para que a operação flua sem silos, retrabalho e atritos.",
        card_integrate_btn: "Ver Integrate",
        card_data_h3: "Dados e IA Aplicada",
        card_data_p: "Transformamos seus dados em conhecimento acionável. Decisões mais rápidas, precisas e estratégicas com impacto direto na sua operação.",
        card_data_btn: "Ver Data+AI",
        card_secure_h3: "Cibersegurança Integral",
        card_secure_p: "Projetamos segurança multinuvem com controle de acesso, backup inteligente e monitoramento contínuo. Menos risco, mais continuidade e visibilidade total.",
        card_secure_btn: "Ver Secure",
        card_sap_h3: "Profunda Expertise em SAP",
        card_sap_p: "+20 anos de experiência real em SAP Business One e SAP ECC. Implementamos e otimizamos com critério e conhecimento de processos. Resultados desde o primeiro dia.",
        card_sap_btn: "Ver SAP",
        partners_h2: "Aliados que constroem um futuro com a Lamarr",
        
        // --- Claves de Mapa y Tabla (ACTUALIZADAS) ---
        map_h3: "Presença e Capacidade Global", // MODIFICADO

        // NUEVAS Claves para la tabla de index.html
        map_table_row1_title: "Chile",
        map_table_row1_desc: "HeadQuarters",
        map_table_row2_title: "Brasil, Costa Rica & Venezuela",
        map_table_row2_desc: "Projetos SAP, Integração, Operação Multicloud, Suporte Regional",
        map_table_row3_title: "Miami",
        map_table_row3_desc: "Hub de alianças",
        map_table_row4_title: "Índia",
        map_table_row4_desc: "Acelerador de desenvolvimento",

        map_footer_h4: "Nosso Compromisso",
        map_footer_q: "\"Seu negócio, impulsionado pela experiência global e compromisso real\"",
        
        // --- Página: contact.html ---
        contact_h2: "Vamos Iniciar a Conversa",
        contact_p1: "Você explorou nossa inovação global em IA e nossa execução especializada em Nuvem e SAP. Viu como transformamos dados em resultados para líderes da indústria.",
        contact_p2: "Agora, é a sua vez. Toda grande transformação começa com uma simples conversa. Seja um desafio complexo de migração, um projeto de IA ou uma consulta sobre otimização, nossa equipe está pronta para ouvi-lo.",
        form_name: "Nome",
        form_lastname: "Sobrenome",
        form_email: "Endereço de e-mail",
        form_phone: "Telefone (Opcional)",
        form_company: "Nome da Empresa (Opcional)",
        form_role: "Cargo (Opcional)",
        form_service: "Serviço de Interesse",
        form_service_option: "Selecione um serviço de interesse...",
        form_message: "Mensagem",
        form_submit_btn: "Enviar",
        // NUEVA CLAVE DE CONFIANZA (Punto 2)
        form_response_time: "Você receberá uma resposta de um especialista em menos de 24 horas úteis.",
        // Fin Nueva Clave
        contact_info_h2: "Informações Diretas",
        contact_info_company: "Razão Social:", // NUEVA
        contact_info_rut: "RUT:", // NUEVA
        contact_info_giro: "Atividade Econômica:", // NUEVA
        contact_info_phone: "Telefone:",
        contact_info_email: "Email:",
        contact_info_address: "Endereço:", // ACTUALIZADA
        popup_title: "Obrigado por nos contatar!",
        popup_p: "Sua mensagem foi enviada. Para um atendimento más rápido, você pode nos contatar diretamente pelo WhatsApp.",
        popup_btn: "Falar pelo WhatsApp",

        // --- Página: lamarr-cloud.html ---
        cloud_h1: "LAMARR | NUVEM",
        cloud_p1: "<strong>Infraestrutura sem atritos.</strong><br>Projetamos, migramos e gerenciamos sua arquitetura na AWS, Google Cloud Platform e Huawei Cloud.",
        cloud_p2: "Não acreditamos em \"tamanho único\". Selecionamos a nuvem (ou nuvens) que melhor se adapta à sua carga de trabalho (SAP, aplicativos, dados), otimizando custos e garantindo um desempenho superior.",
        cloud_s1_h2: "Nossas Capacidades de Nuvem",
        cloud_s1_c1_h3: "Migração e Modernização",
        cloud_s1_c1_p: "Planos de migração (Lift & Shift, Re-platform) e modernização de aplicativos (contêineres, serverless) sem interromper seu negócio.",
        cloud_s1_c2_h3: "FinOps e Otimização de Custos",
        cloud_s1_c2_p: "Auditoria contínua de seus gastos com nuvem. Implementamos estratégias FinOps para eliminar desperdícios e reducir sua fatura mensal.",
        cloud_s1_c3_h3: "Serviços Gerenciados e DevSecOps",
        cloud_s1_c3_p: "Monitoramento 24/7, gerenciamento de patches, segurança e automação de pipelines CI/CD. Cuidamos da operação para que você possa focar na inovação.",
        cloud_s1_c4_h3: "Arquitetura SAP na Nuvem",
        cloud_s1_c4_p: "Projetamos arquiteturas de alta disponibilidade (HA/DR) para SAP S/4HANA e B1 em nuvens públicas, certificadas e com desempenho otimizado.",
        cloud_s1_btn: "Inicie sua migração para a nuvem",

        // --- Página: lamarr-data-ai.html ---
        data_h1: "LAMARR | DATA+AI",
        data_p1: "Inteligência que transforma dados em decisões reais. Integramos nossa experiência técnica com soluções de IA comprovadas, para que seu negócio possa escalar com IA desde o primeiro dia.",
        data_s1_h3: "Filosofia 360: Múltiplos Pontos de Entrada, Uma Direção",
        data_s1_p: "Entendemos que cada empresa está em um estágio diferente. Nossa \"Filosofia 360\" nos permite agregar valor com IA independentemente do seu ponto de partida, acompanhando desde a estratégia até a execução e o dimensionamento.",
        data_s2_h2: "Estágios de Maturidade",
        data_s2_c1_h3: "DATA READINESS",
        data_s2_c1_p: "Avaliamos seu ponto de partida para usar IA com sucesso. Realizamos um diagnóstico que analisa sua maturidade tecnológica, a qualidade de seus dados e o alinhamento de sua estratégia de IA com os objetivos de negócio.",
        data_s2_c2_h3: "DATALAKE",
        data_s2_c2_p: "Centralize todos os seus dados em uma base segura e escalável. Integramos informações de SAP, CRM, ERP, planilhas, aplicativos web e sensores IoT em um único ambiente limpo e pronto para análise.",
        data_s2_c3_h3: "PREDICT & INSIGHTS",
        data_s2_c3_p: "Veja o que está acontecendo e o que está por vir. Com modelos preditivos e análise avançada, detectamos padrões, antecipamos comportamentos e geramos recomendações práticas.",
        data_s2_c4_h3: "AI SOLUTIONS",
        data_s2_c4_p: "Soluções Plug & Play de IA prontas para usar (scaleAssist, scaleRep) que se integram imediatamente aos seus procesos-chave, sem desenvolvimentos intermináveis ou altos investimentos iniciais.",
        data_s2_c5_h3: "AI FACTORY",
        data_s2_c5_p: "Desenvolvimento sob medida para sua indústria. Colocamos à sua disposição equipes especializadas em Gen AI, Machine Learning e Data Science para criar soluções únicas.",
        data_s2_c6_h3: "DATA 360",
        data_s2_c6_p: "Seu ecossistema completo de dados e IA, sob controle. Combine todas as nossas solutions em um ambiente único, escalável e seguro na AWS, Google Cloud Platform ou Huawei Cloud.",
        data_s3_h2: "Soluções de IA Plug & Play",
        data_s3_t_h1: "Solução",
        data_s3_t_h2: "O que faz",
        data_s3_t_h3: "Benefício imediato",
        data_s3_t_r1_d1: "Unifica dados de CRM, ERP e fontes externas para uma visão completa.",
        data_s3_t_r1_d2: "Decisões mais rápidas e precisas.",
        data_s3_t_r2_d1: "Agentes de voz com IA que qualificam leads e realizam pesquisas 24/7.",
        data_s3_t_r2_d2: "Vendas automatizadas e melhor experiência do cliente.",
        data_s3_t_r3_d1: "Recrutamento inteligente: IA que entrevista, analisa e recomenda.",
        data_s3_t_r3_d2: "Seleção mais rápida e com menos viés.",
        data_s3_t_r4_d1: "Converte apresentações em cursos com narração e avaliação de IA.",
        data_s3_t_r4_d2: "Treinamento interno ágil e contínuo.",
        data_s3_t_r5_d1: "Automatiza gerenciamento de documentos e validação com IA.",
        data_s3_t_r5_d2: "Economia de tempo e detecção de fraudes.",
        data_s3_btn: "Solicite uma Avaliação",

        // --- Página: lamarr-integrate.html ---
        integrate_h1: "LAMARR | INTEGRATE",
        integrate_p1: "Conectamos seus sistemas, dados e aplicativos. Criamos fluxos de informação fluidos entre SAP, suas plataformas de nuvem e aplicativos de terceiros para uma operação unificada.",
        integrate_s1_h2: "Integre seu Ecossistema Tecnológico",
        integrate_s1_p: "No centro da transformação digital está a integração. O LAMARR | INTEGRATE garante que seus aplicativos críticos (ERP, CRM, SCM) se comuniquem de forma eficiente, eliminando silos de dados e automatizando processos de negócios de ponta a ponta.",
        integrate_s1_l1: "<strong>SAP Cloud Platform Integration (CPI):</strong> Desenho e gerenciamento de fluxos de integração.",
        integrate_s1_l2: "<strong>Conectividade Híbrida:</strong> Unificamos seus ambientes On-Premise e Multi-Cloud.",
        integrate_s1_l3: "<strong>Integración de APIs:</strong> Criamos e gerenciamos APIs para conectar seus serviços.",
        integrate_s1_l4: "<strong>Fluxos de Dados (ETL/ELT):</strong> Movemos seus dados com segurança para análise e IA.",
        integrate_s1_btn: "Conecte seu ecossistema hoje",

        // --- Página: lamarr-secure.html ---
        secure_h1: "LAMARR | SECURE",
        secure_p1: "Ciberproteção nativa para o seu negócio. Oferecemos uma plataforma integrada de backup, DR, segurança avançada e monitoramento contínuo, impulsionada pelas melhores alianças tecnológicas, para proteger seus dados, aplicativos e sistemas.",
        secure_s1_h2: "Produtos e Serviços de Ciberproteção",
        secure_s1_c1_h3: "Cyber Backup & Recovery",
        secure_s1_c1_p: "Backups rápidos e confiáveis de qualquer carga de trabalho. Armazenamento seguro em nossa nuvem, AWS, GCP ou local, com restauração instantânea de dados críticos.",
        secure_s1_c2_h3: "Disaster Recovery (DRaaS)",
        secure_s1_c2_p: "Recuperação de desastres como serviço. Minimize o tempo de inatividade e garanta a continuidade dos negócios com failover para nossa plataforma em nuvem.",
        secure_s1_c3_h3: "Advanced Security",
        secure_s1_c3_p: "Proteção proativa contra ransomware e malware impulsionada por IA. Antivírus, antimalware e análise de vulnerabilidades em uma única solution.",
        secure_s1_c4_h3: "Endpoint Defense",
        secure_s1_c4_p: "Proteção inteligente em cada dispositivo. Proteção com IA para estações de trabalho e servidores contra malware, phishing e ameaças desconhecidas.",
        secure_s1_c5_h3: "SaaS Protect",
        secure_s1_c5_p: "Proteção completa para Microsoft 365 e Google Workspace. Garantimos backups nuvem a nuvem para e-mails, arquivos (OneDrive, SharePoint) e colaborações (Teams).",
        secure_s1_btn: "Agende uma avaliação",

        // --- Página: noticias.html ---
        news_h1: "Notícias: O que estamos construindo",
        news_p1: "Crescemos junto com nossos parceiros, nossos clientes e nossa comunidade. Cada passo fortalece nossa capacidade de entregar soluções integradas, seguras e escaláveis em SAP, Nuvem e IA.",
        news_s1_h2: "Novas Alianças Estratégicas",
        news_s1_c1_h3: "Lamarr + WIT: Aliança para Desenvolvimento de Novos Negócios",
        news_s1_c1_p: "Formalizamos uma aliança com a WIT para fortalecer a abertura e qualificação de oportunidades comerciais no Chile e LATAM. Este trabalho conjunto nos permite alcançar empresas que buscam modernizar o SAP e escalar para arquiteturas multicloud, com acompanhamento consultivo e visão estratégica.",
        news_s1_c2_h3: "Lamarr + La Araucaria Software: Soluções Conjuntas em Cibersegurança",
        news_s1_c2_p: "Juntamente com La Araucaria Software, estamos desenvolvendo soluções voltadas para cibersegurança aplicada, proteção de dados críticos e monitoramento inteligente de riscos. A combinação de engenharia segura + integração SAP + arquitetura em nuvem nos permite entregar soluções escaláveis, eficientes e alinhadas aos desafios atuais.",
        news_s1_c3_h3: "Acordo Marco com a Noventiq",
        news_s1_c3_p: "Este acordo formaliza nossa capacidade de executar projetos SAP + Cloud em conjunto, garantindo continuidade, rastreabilidade e escalabilidade na entrega de serviços.",
        news_s2_h2: "Eventos e Notícias Passadas",
        news_s2_c1_h3: "Huawei Cloud reconhece a Lamarr como Parceira com Potencial",
        news_s2_c1_p: "A Lamarr participou do Huawei Cloud Summit, onde fomos reconhecidos como Parceira com Potencial na região por nossa experiência em modernização SAP, estratégias multicloud e arquiteturas híbridas. Este marco reflete nosso compromisso com soluções de alto impacto, com execução técnica própria e acompanhamento contínuo.",
        news_s2_c1_alt: "Certificado de Parceiro Huawei Cloud Lamarr Tech", 
        news_s2_c2_h3: "Evento Presencial: SAP Business One na Huawei Cloud",
        news_s2_c2_p: "Realizamos um encontro executivo voltado para organizações que operam SAP Business One e desejam migrar ou otimizar sua infraestrutura na nuvem, mantendo a continuidade operacional e o controle de custos. Apresentamos rotas de transição, casos reais e modelos de arquitetura.",
        news_s2_c2_btn: "Ler mais e ver vídeo",
        news_s2_c3_h3: "Webinar Executivo com a Noventiq: O Fim do Suporte ao SAP ECC",
        news_s2_c3_p: "Em um recente encontro executivo, conversamos com a Noventiq sobre o fim do suporte ao SAP ECC, suas implicações e as opções de transição para o SAP na nuvem. O foco foi claro: tomar decisões informadas, não apressadas.",
        
        // --- UPDATE: Portuguese Text for SAP B1 Webinar ---
        news_s3_h2: "Próximos Eventos",
        news_s3_c1_h3: "Webinar Exclusivo: Potencialize seu SAP Business One na Nuvem",
        news_s3_c1_s: "Estratégias de Migração, Otimização e Economia",
        news_s3_c1_p: "<strong>Sua infraestrutura atual limita o crescimento do seu negócio?</strong><br>Descubra como migrar o SAP Business One para a nuvem pode reduzir custos operacionais, melhorar a segurança e garantir a continuidade da sua operação. Nesta sessão, exploraremos as rotas de migração mais eficientes e como aproveitar ao máximo as capacidades da nuvem.",
        news_s3_c1_l1: "<strong>Migração sem atritos:</strong> Passos-chave para uma transição segura.",
        news_s3_c1_l2: "<strong>Economia e Desempenho:</strong> Como otimizar recursos e melhorar a velocidade.",
        news_s3_c1_l3: "<strong>Casos de Sucesso:</strong> Empresas que já transformaram sua operação.",
        news_s3_c1_btn: "→ Reserve sua vaga agora",
        // -----------------------------------------------

        news_cierre: "Na Lamarr, avançamos com uma visão clara:<br>Tecnologia integrada. Operação fluida.<br>Execução responsável e acompanhamento real.",
        news_cta_h3: "Não perca nossos futuros convites",
        news_cta_p: "Se você não quer perder nossos próximos eventos e quer ser convidado diretamente em seu e-mail, cadastre-se em nossa página de contato.",
        news_cta_btn: "Inscreva-se aqui",

        // --- Página: nuestro-equipo.html ---
        team_h1: "Nossa Equipe",
        team_p1: "Conheça os líderes e as unidades que impulsionam a inovação na Lamarr Tech.",
        team_s1_h2: "Direção e Estratégia",
        team_s1_c1_h3: "Daniela Santos Escalona",
        team_s1_c1_r: "Founder & CEO | Gerente Comercial",
        team_s1_c1_p: "Lidera a estratégia global da Lamarr Tech, alianças com AWS, Google Cloud Platform e Huawei, desenvolvimento de mercado e relacionamento direto com clientes de médio e grande porte. Responsável pelo posicionamento comercial, propostas de valor, negociações e fechamento de oportunidades estratégicas.",
        team_s1_c2_h3: "Alcides Lizardo",
        team_s1_c2_r: "Co-Founder | Diretor de Operações e Finanças",
        team_s1_c2_p: "Responsável pela operação interna de projetos, finanças, controle de custos, contratação de pessoal, relacionamento com fornecedores e garantia de qualidade. Supervisiona as áreas técnicas e o cumprimento dos SLAs em serviços gerenciados.",
        team_s2_h2: "Unidade LAMARR | CLOUD",
        team_s2_p: "(Infraestrutura, migrações e suporte Cloud – AWS, Google Cloud Platform, Huawei Cloud)",
        team_s2_c1_h3: "Arquiteto de Nuvem / Líder Técnico",
        team_s2_c1_r: "(Papel variável por projeto)",
        team_s2_c1_p: "Projeto de arquiteturas em nuvem, avaliações de infraestrutura (AWS OLA, MAP, GCP Assessment), planos de migração e suporte avanzado. (Este papel pode ser personalizado por projeto: Ex. Arquiteto AWS Sênior, Arquiteto GCP, etc.)",
        team_s2_c2_h3: "Consultores de Nuvem e DevOps",
        team_s2_c2_r: "Implementação e Operação",
        team_s2_c2_p: "Implementação de ambientes, automação, otimização de custos, monitoramento, backup & DRP, segurança gerenciada e administração diária de plataformas em nuvem.",
        team_s3_h2: "Unidade LAMARR | SAP",
        team_s3_p: "(Consultoria, suporte e migrações SAP Business One & SAP S/4HANA)",
        team_s3_c1_h3: "Consultor SAP Business One Sênior",
        team_s3_c1_r: "Funcional e Processos",
        team_s3_c1_p: "Lidera diagnósticos funcionais, mapeamento de processos, parametrização e melhorias operacionais.",
        team_s3_c2_h3: "Consultor SAP Business One Técnico / Basis",
        team_s3_c2_r: "Administração e Suporte Técnico",
        team_s3_c2_p: "Administração de servidores SAP B1, instalação, upgrades, ajuste de desempenho e suporte técnico.",
        team_s3_c3_h3: "Consultor de Integrações SAP",
        team_s3_c3_r: "(SAP BTP / APIs / Conectores)",
        team_s3_c3_p: "Projeto e implementação de integrações entre SAP e sistemas externos (ERP, logística, finanças, BI, IA).",
        team_s4_h2: "Unidade DATA + AI | Inteligência e Automação",
        team_s4_p: "(Modelos preditivos, relatórios financeiros, dashboards e RPA/IA)",
        team_s4_c1_h3: "Engenheiro de Dados / Especialista em BI",
        team_s4_c1_r: "Engenharia e Visualização",
        team_s4_c1_p: "Modelagem de dados, construção de ETL, dashboards dinámicos (Power BI, Looker, ModelArts, QuickSight).",
        team_s4_c2_h3: "Especialista em IA Aplicada",
        team_s4_c2_r: "Automação Inteligente",
        team_s4_c2_p: "Automação de processos, geração de relatórios inteligentes, assistentes empresariais e motores de análise baseados em IA.",
        team_s5_h2: "Unidade de Administração e Controle",
        team_s5_c1_h3: "Coordenação Administrativa",
        team_s5_c1_r: "Gestão e Finanças",
        team_s5_c1_p: "Gestão de fornecedores, controle de pagamentos, emissão de documentos contábeis, relatórios internos, conciliações e suporte administrativo às unidades de negócio.",
        team_s5_c2_h3: "Suporte Operacional e Gerenciamento de Projetos",
        team_s5_c2_r: "Planejamento e Acompanhamento",
        team_s5_c2_p: "Planejamento de tarefas, coordenação entre equipe técnica e clientes, acompanhamento de SLAs e entregáveis.",

        // --- Página: services-sap.html ---
        sap_h1: "LAMARR | SAP",
        sap_s1: "O poder do SAP, levado ao seu máximo desempenho.",
        sap_p1: "Acompanhamos empresas que operam SAP a evoluir para um sistema mais eficiente, integrado e preparado para crescer.",
        sap_p2: "Combinamos experiência operacional em SAP com domínio das novas soluções SAP BTP para integrar, automatizar e escalar seu negócio. Projetamos ambientes SAP que se adaptam à sua estratégia, e não o contrário.",
        sap_s2_h2: "Nossos Serviços SAP",
        sap_s2_c1_h3: "Consultoria Funcional e Melhoria de Processos",
        sap_s2_c1_p: "Otimizamos sua operação financeira, logística, contábil e de suprimentos para simplificar, controlar e acelerar tarefas-chave.",
        sap_s2_c2_h3: "Implementação e Atualização de Versões",
        sap_s2_c2_l1: "Implementação e reparametrização no SAP Business One",
        sap_s2_c2_l2: "Migração para o SAP B1 10.0 (SQL / HANA)",
        sap_s2_c2_l3: "Evolução do SAP ECC para o S/4 HANA",
        sap_s2_c3_h3: "Suporte Técnico e Desempenho SAP",
        sap_s2_c3_p: "Administração de bancos de dados, tuning, resolução de incidentes e continuidade operacional. Estabilidade e desempenho 24/7.",
        sap_s2_c4_h3: "SAP BTP e Conectividade",
        sap_s2_c4_p: "Integramos o SAP com CRM, e-commerce, aplicativos internos e nuvem. Automação, APIs, workflows e dados centralizados.",
        sap_s2_c5_h3: "SAP na Nuvem (AWS, Google Cloud Platform, Huawei Cloud)",
        sap_s2_c5_p: "Arquiteturas seguras, escaláveis e de alta disponibilidade, com otimização FinOps para reduzir custos.",
        sap_s3_h2: "Casos Reais",
        sap_s3_l1: "Migramos o SAP Business One para a AWS, reduzindo custos em 35% e habilitando acesso remoto seguro para todas as áreas.",
        sap_s3_l2: "Integração SAP + e-commerce, alcançando atualização automática de estoques e pedidos em tempo real.",
        sap_s3_l3: "Otimização de processos financeiros no SAP ECC, reduzindo o tempo de fechamento contábil em 60%.",
        sap_p3: "Seu SAP pode ser mais eficiente, mais conectado e mais rentável. Nós o acompanhamos no caminho.",
        sap_s3_btn: "Sua evolução SAP começa aqui."
    }
};